#Argumentos para topologia do slide
x-terminal-emulator -e python3 eleicao.py 0
x-terminal-emulator -e python3 eleicao.py 1
x-terminal-emulator -e python3 eleicao.py 2
x-terminal-emulator -e python3 eleicao.py 3
x-terminal-emulator -e python3 eleicao.py 4
x-terminal-emulator -e python3 eleicao.py 5
x-terminal-emulator -e python3 eleicao.py 6
x-terminal-emulator -e python3 eleicao.py 7
x-terminal-emulator -e python3 eleicao.py 8
x-terminal-emulator -e python3 eleicao.py 9